baseURL = "https://securefirmware.de"
languageCode = 'en-us'
title = 'EMBA BEYOND'
theme="archie"
googleAnalytics = 'G-8PK23K2LEL'

[params]
mode="dark" # color-mode → light,dark,toggle or auto
subtitle = "The firmware scanning environment with [EMBA](https://github.com/e-m-b-a/emba) and [EMBArk](https://github.com/e-m-b-a/embark)"
customcss = ["css/style.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/e-m-b-a"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/securefirmware/"

[[menu.main]]
  name = "Blog"
  identifier = "posts"
  url = "/posts/"
  
#[[menu.main]]
#  name = "EMBA"
#  identifier = "emba"
#  url = "/wiki/emba/"
  
#[[menu.main]]
#  name = "EMBArk"
#  identifier = "embark"
#  url = "/wiki/embark/"
  
