baseURL = "https://e-m-b-a.github.io/public"
languageCode = 'en-us'
title = 'E-M-B-A The firmware scanning environment'
theme="archie"

[params]
	mode="auto" # color-mode → light,dark,toggle or auto

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/m-1-k-3"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/securefirmware/"
